name       : libwacom
version    : 1.7.0
release    : 22
source     :
    - https://github.com/linuxwacom/libwacom/archive/libwacom-1.7.tar.gz : 0e15b127f999cdf5988dc398bd4c92ae6f85347b2ec9e794f8e8148b7b070011
license    : MIT
component  : desktop.core
homepage   : https://github.com/linuxwacom/libwacom/
summary    : A library used to identify wacom tablets and their model-specific features
description: |
    libwacom is a library to identify Wacom tablets and their model-specific features. It provides easy access to information such as "is this a built-in on-screen tablet", "what is the size of this model", etc.
builddeps  :
    - python-libevdev
    - python-pytest
    - python3-pyudev
rundeps    :
    - python-libevdev
setup      : |
    %patch -p1 < $pkgfiles/fix-typo-in-tests.patch
    sed -i "s|pytest-3|pytest3|g" meson.build
    rm -f test/test_udev_rules.py

    %meson_configure -Dudev-dir=%libdir%/udev/
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
