name       : libwacom
version    : 1.4.1
release    : 19
source     :
    - https://github.com/linuxwacom/libwacom/archive/libwacom-1.4.1.tar.gz : 87c3d4282b84d27896afad0b69656aec1045593370978403ab0a66d1f02f3ff5
license    : MIT
summary    : The libwacom package contains a library used to identify wacom tablets and their model-specific features.
description: |
    libwacom is a library to identify Wacom tablets and their model-specific features. It provides easy access to information such as "is this a built-in on-screen tablet", "what is the size of this model", etc.
component  : desktop.core
setup      : |
    %meson_configure -Dudev-dir=%libdir%/udev/
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
