name       : libwacom
version    : '0.27'
release    : 12
source     :
    - https://sourceforge.net/projects/linuxwacom/files/libwacom/libwacom-0.27.tar.bz2 : f340d0010cc5dece8e4523b1e3220a98cba7939450ddbc017e86a134ceaece14
license    :
    - MIT
summary    : The libwacom package contains a library used to identify wacom tablets and their model-specific features.
description: |
    The libwacom package contains a library used to identify wacom tablets and their model-specific features.
component  : desktop.core
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
