name        : libwacom
version     : 0.17
release     : 7
source     :
    - http://downloads.sourceforge.net/linuxwacom/libwacom-0.17.tar.bz2 : 89517967f7fb3b4c4774893b041b09ea3574e46beb97815a43885cc387d57525
license     :
    - MIT
summary     : The libwacom package contains a library used to identify wacom tablets and their model-specific features.
description : |
    The libwacom package contains a library used to identify wacom tablets and their model-specific features.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
