name       : libwacom
version    : '0.33'
release    : 17
source     :
    - https://github.com/linuxwacom/libwacom/archive/libwacom-0.33.tar.gz : 0e906e6af1fcd2ed6e7427b0b3706c002fcdd34d5face51e67578734fd80c2f9
license    :
    - MIT
summary    : The libwacom package contains a library used to identify wacom tablets and their model-specific features.
description: |
    The libwacom package contains a library used to identify wacom tablets and their model-specific features.
component  : desktop.core
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
    pushd tools
      install -dm00755 $installdir/usr/lib64/udev/rules.d
      ./generate-udev-rules > $installdir/usr/lib64/udev/rules.d/65-libwacom.rules
    popd
check      : |
    %make check
