name       : libwacom
version    : 1.11.0
release    : 27
source     :
    - https://github.com/linuxwacom/libwacom/archive/refs/tags/libwacom-1.11.tar.gz : cb4578c1b72efe13af4212fff737221ae937b42920e4ced2ee659a8d9a40a12a
license    : MIT
component  : desktop.core
homepage   : https://github.com/linuxwacom/libwacom/
summary    : A library used to identify wacom tablets and their model-specific features
description: |
    libwacom is a library to identify Wacom tablets and their model-specific features. It provides easy access to information such as "is this a built-in on-screen tablet", "what is the size of this model", etc.
builddeps  :
    - python-libevdev
    - python-pytest
    - python3-pyudev
rundeps    :
    - python-libevdev
    - python3-pyudev
setup      : |
    sed -i "s|pytest-3|pytest3|g" meson.build
    rm -f test/test_udev_rules.py

    %meson_configure -Dudev-dir=%libdir%/udev/
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
