name       : libwacom
version    : 2.8.0
release    : 33
source     :
    - https://github.com/linuxwacom/libwacom/releases/download/libwacom-2.8.0/libwacom-2.8.0.tar.xz : bb04b12c8688d0ff6a108d47a38d2057d572c4d7227d78138abd5fd0ba59f215
license    : MIT
component  : desktop.core
homepage   : https://github.com/linuxwacom/libwacom/
summary    : A library used to identify wacom tablets and their model-specific features
description: |
    libwacom is a library to identify Wacom tablets and their model-specific features. It provides easy access to information such as "is this a built-in on-screen tablet", "what is the size of this model", etc.
builddeps  :
    - python-libevdev
    - python-pytest
    - python3-pyudev
rundeps    :
    - python-libevdev
    - python3-pyudev
setup      : |
    sed -i "s|pytest-3|pytest3|g" meson.build
    rm -f test/test_udev_rules.py

    %meson_configure -Dudev-dir=%libdir%/udev/
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
