name       : libwacom
version    : '1.5'
release    : 20
source     :
    - https://github.com/linuxwacom/libwacom/archive/libwacom-1.5.tar.gz : d81f8330901657e590369d296e3f97f9a5a143f519b3375c0b6ac5c70db3c2f3
license    : MIT
summary    : The libwacom package contains a library used to identify wacom tablets and their model-specific features.
description: |
    libwacom is a library to identify Wacom tablets and their model-specific features. It provides easy access to information such as "is this a built-in on-screen tablet", "what is the size of this model", etc.
component  : desktop.core
setup      : |
    %meson_configure -Dudev-dir=%libdir%/udev/
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
