name       : libwacom
version    : '1.1'
release    : 18
source     :
    - https://github.com/linuxwacom/libwacom/releases/download/libwacom-1.1/libwacom-1.1.tar.bz2 : 8cb483593676332e92d3fe1fe816350f136bb906fcee329579d6cb9802d99e02
license    : MIT
summary    : The libwacom package contains a library used to identify wacom tablets and their model-specific features.
description: |
    libwacom is a library to identify Wacom tablets and their model-specific features. It provides easy access to information such as "is this a built-in on-screen tablet", "what is the size of this model", etc.
component  : desktop.core
setup      : |
    %meson_configure -Dudev-dir=%libdir%/udev/
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
