name       : libwacom
version    : 1.6.0
release    : 21
source     :
    - https://github.com/linuxwacom/libwacom/archive/libwacom-1.6.tar.gz : 987b8fbadf248327bf15f7988772cf03e5fb96e5094df0428e6a22ec1aab8419
license    : MIT
component  : desktop.core
homepage   : https://github.com/linuxwacom/libwacom/
summary    : A library used to identify wacom tablets and their model-specific features
description: |
    libwacom is a library to identify Wacom tablets and their model-specific features. It provides easy access to information such as "is this a built-in on-screen tablet", "what is the size of this model", etc.
setup      : |
    %meson_configure -Dudev-dir=%libdir%/udev/
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
