name       : libwacom
version    : 2.4.0
release    : 31
source     :
    - https://github.com/linuxwacom/libwacom/releases/download/libwacom-2.4.0/libwacom-2.4.0.tar.xz : d0d022761e3f9ab23e329583b7d2bd470b0450dfb077caeb22c5a0d66c2bd414
license    : MIT
component  : desktop.core
homepage   : https://github.com/linuxwacom/libwacom/
summary    : A library used to identify wacom tablets and their model-specific features
description: |
    libwacom is a library to identify Wacom tablets and their model-specific features. It provides easy access to information such as "is this a built-in on-screen tablet", "what is the size of this model", etc.
builddeps  :
    - python-libevdev
    - python-pytest
    - python3-pyudev
rundeps    :
    - python-libevdev
    - python3-pyudev
setup      : |
    sed -i "s|pytest-3|pytest3|g" meson.build
    rm -f test/test_udev_rules.py

    %meson_configure -Dudev-dir=%libdir%/udev/
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
