name       : libwacom
version    : '0.30'
release    : 14
source     :
    - https://github.com/linuxwacom/libwacom/releases/download/libwacom-0.30/libwacom-0.30.tar.bz2 : 523408680514c0f01052e478503d8e89f86d72ddc7129fdd63988c221c492259
license    :
    - MIT
summary    : The libwacom package contains a library used to identify wacom tablets and their model-specific features.
description: |
    The libwacom package contains a library used to identify wacom tablets and their model-specific features.
component  : desktop.core
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    pushd tools
      install -dm00755 $installdir/usr/lib64/udev/rules.d
      ./generate-udev-rules > $installdir/usr/lib64/udev/rules.d/65-libwacom.rules
    popd
check      : |
    %make check
